name: Traffic Light Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      result:
        description: 'Set to fail to simulate a failing build (success|fail)'
        required: false
        default: 'success'

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Show context
      run: |
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Ref: $GITHUB_REF"
        echo "Event: $GITHUB_EVENT_NAME"

    - name: Simulate success
      if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.result != 'fail' }}
      run: echo "Success ✅"

    - name: Simulate failure
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.result == 'fail' }}
      run: |
        echo "Failure ❌"
        exit 1
